// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DaterangePickerController from "./daterange_picker_controller"
application.register("daterange-picker", DaterangePickerController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import UserPaymentsController from "./user_payments_controller"
application.register("user-payments", UserPaymentsController)
